---
name: Release

on:
  push:
    branches:
      - main

jobs:
  Please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: elixir
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          extra-files: README.md
