name: Release

on:
  release:
    types:
      - published

env:
  CACHE_VERSION: v1
  ELIXIR_VERSION: "1.13"
  OTP_VERSION: "25"

jobs:
  Hex:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}
      - id: cache
        uses: actions/cache@v3
        with:
          key: |
            ${{ env.CACHE_VERSION }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-release-{{ hashFiles('mix.lock') }}-${{ github.ref }}
          restore-keys: |
            ${{ env.CACHE_VERSION }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-release-{{ hashFiles('mix.lock') }}-${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
            ${{ env.CACHE_VERSION }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-release-
            ${{ env.CACHE_VERSION }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-
          path: |
            _build
            deps
      - if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get
      - run: mix compile --docs
      - run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
